name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build-and-test-dev-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker prod image
        run: make build-prod

      - name: Build docker dev image
        run: make build-dev

      - name: Build the stack
        run: docker-compose -f "docker-compose.dev.yml" up -d
